#!/usr/bin/perl
###############

##
#         Name: msfpayload
#       Author: H D Moore <hdm [at] metasploit.com>
#      Version: $Revision$
#  Description: Command line interface for generating Metasploit payloads
#      License:
#
#      This file is part of the Metasploit Exploit Framework
#      and is subject to the same licenses and copyrights as
#      the rest of this package.
#
##

require 5.6.0;

use strict;

use FindBin qw{$Bin};
use POSIX;

use lib "$Bin/lib";
use Msf::TextUI;
use Pex;

Msf::UI::ActiveStateSucks();

my $ui = Msf::TextUI->new($Bin);
my $VERSION = $ui->Version;

$ui->SetTempEnv('_MsfPayload', 1);

my $exploits = { };
my $payloads = { };
my $exploitsIndex = $ui->LoadExploits;
my $payloadsIndex = $ui->LoadPayloads;
my $encoders = $ui->LoadEncoders;
my $nops     = $ui->LoadNops;

foreach my $key (keys(%{$payloadsIndex})) {
    $payloads->{$payloadsIndex->{$key}->Name} = $payloadsIndex->{$key};
}

foreach my $key (keys(%{$exploitsIndex})) {
    $exploits->{$exploitsIndex->{$key}->Name} = $exploitsIndex->{$key};
}

$ui->SetTempEnv('_Exploits', $exploitsIndex);
$ui->SetTempEnv('_Payloads', $payloadsIndex);
$ui->SetTempEnv('_Encoders', $encoders);
$ui->SetTempEnv('_Nops', $nops);

my $sel = shift();
my $p = $payloads->{$sel};
Usage() if ! $p;

my $opt = {};
my $idx = 0;

while ( my ($k, $v) = split(/\=/, shift()) )
{
    if (! defined($v))
    {
        $opt->{"ARG".$idx} = uc($k);
        $idx++;
    } else {
        $ui->SetTempEnv($k, $v);
    }   
}

$ui->SetTempEnv('_Exploit', $exploits->{'Tester'});
$ui->SetTempEnv('_PayloadName', $sel);
$ui->SetTempEnv('_Payload', $p);

my $action = uc($opt->{'ARG0'});

if (! $action || $action =~ /^S/)
{
    print "\n";
    print "        Name: $sel\n";
    print "     Version: " . $p->Version . "\n";
    print "     Authors: " . join(" ", @{$p->Authors}) . "\n";
    print "Architecture: " . join(" ", @{$p->Arch}) . "\n";
    print "  Privileged: " . ($p->Priv ? "Yes" : "No") . "\n";
    print "  Multistage: " . ($p->Multistage ? "Yes" : "No") . "\n";
    print "Supported OS: " . join(" ", @{$p->OS()}) . "\n";
    print "Handler Type: " . $p->Type . "\n";
    print "  Total Size: " . $p->Size . "\n\n";
    
    if (scalar(keys(%{$p->UserOpts})))
    {
        foreach my $o (keys(%{$p->UserOpts}))
        {
            print "\t" . $o . (" " x (20 - length($o))) . ($p->UserOpts->{$o}->[0] ? "Y" : "N") .
                  "\t" . $p->UserOpts->{$o}->[1] . "\t" . $p->UserOpts->{$o}->[2] . "\n";
        }
    }
    print "\n";
    exit(0);
}

Usage() if $action !~ /^C|^P|^R/;

my $s = $ui->Encode;
if (! $s)
{
    print "Error: " . $ui->Error() . "\n";
    exit(0);
}

if ($action =~ /^R/) { print $s->RawPayload; exit; }

if ($p->Multistage)
{
    print STDERR "Warning: Multistage payloads only return first stage\n\n";
}

my $r = $action =~ /^C/ ? Pex::Utils::BufferC($s->RawPayload) : Pex::Utils::BufferPerl($s->RawPayload);

print $r;
exit(0);

sub Usage
{
    print STDERR "   Usage: $0 <payload> [var=val] <S|C|P>\n";
    print STDERR "Payloads: \n";
    foreach my $p (sort(keys(%{$payloads})))
    {
        print STDERR "  $p" . (" " x (25 - length($p))) . $payloads->{$p}->Description . "\n";
    }
    exit(0);
}
